name: CI Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
# Job section
jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim
    # Services section
    services:
      # Postgres service
      postgres:
        image: postgres:alpine
        ports: 
          - 5432:5432
        env:
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
          POSTGRES_DB: testdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retiries 5
    # Steps section
    steps:
      # step to checkout the code
      - name: Checkout
        uses: actions/checkout@2
      # step to install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt
      # step to lint with flake8
      - name: Lint with flake8
        run: |
          flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 service --count --max-complexity=10 --max-line-length=127 --statistics
      # step to add unit testing
      - name: Run unit tests with nose
        run: nosetests
        # add an environment variable
        env:
          DATABASE_URI: "postgresql://postgres:{password}@{service}:{port}/{database}"